version: "3"

services:
  imagereceiver:
    build: 
      context: ./imagereceiver
      dockerfile: Dockerfile-dev
    command: npm run watch
    # image: node
    volumes:
      - ./imagereceiver:/app
    ports:
      - "5000:80"
      - "5858:5858"
  app-viewer:
    # image: node
    build: 
      context: ./viewer-app
      dockerfile: Dockerfile-dev
    volumes:
      - ./viewer-app:/app
    command: npm run start
  proxy:
    image: nginx

